clear
clc

%% init
var_str = {'B_exit',...
'B_s_tu', ...
'B_tu', ...
'B_tu_tup', ...
'B_exit',...
'B_tu',...
'B_in_sgu',...
'B_exit_sgu',...
'B_rec_otsg_bbd',...
'B_pro',...
'cost_fix_s', ...
'cost_fix_tu_a', ...
'cost_fix_tu_b', ...
'Cost_tot_tu', ...
'cost_var_s', ...
'cost_var_tu_a', ...
'cost_var_tu_b', ...
'C_c_s', ...
'C_exit', ...
'C_in', ...
'C_in_max', ...
'C_loss', ...
'C_out', ...
'C_rout', ...
'C_target', ...
'F_in_sgu', ...
'F_exit', ...
'F_in', ...
'F_loss', ...
'F_out', ...
'F_rec', ...
'F_s', ...
'F_s_tu', ...
'HY', ...
'ML_in', ...
'ML_out', ...
'ML_rem_c', ...
'ML_rem_tu_c', ...
'NS_max', ...
'RR', ...
} ;

gdx_file = 'main_loc.gdx';
pref.form = 'full';

for i = 1:length(var_str)
    pref.name = var_str{i};
    exp = [var_str{i},' = rgdx(gdx_file,pref);'];
    eval(exp);
end

%building sets

tu_start = 1;
tu_end = 7;
c_start = 8;
c_end = 11;
s_start = 12;
s_end = 14;

uels = B_s_tu.uels{1,1} ;
for i = 1:length(uels)
    exp = ['i', uels{i}, '= i;'];
    eval(exp);
end

set_tu = uels(tu_start:tu_end);
set_c = uels(c_start:c_end);
set_s = uels(s_start:s_end);

save minlp_main.mat ;


